//alert("Hello World na tela!");

//console.log("Hello World no console!");

let nome = "Heitor";
const idade = 14;
var cidade = "São Paulo";

console.log(nome);
console.log(idade);
console.log(cidade);

console.log("meu nome é: " + nome); // concatenação
console.log('meu nome é: ${nome} '); // interpolação

console.log("Tenho " + idade + " anos ")
console.log("moro em: " + cidade);

let texto = "Tenho 2 celulares";
let numero = 20;

console.log (texto);
console.log(numero);

console.log(typeof idade);

let n1 = 10;
let n2 = 10;

let soma = n1 + n2;

console.log(soma);

